### ISSUE TITLE
[Bug]: Exceptions thrown when no configs are set yet.

### ISSUE THREAD

**Issue by kwvanderlinde** [kwvanderlinde/discordant#2]
### Reproduction steps

1. Add discordant development JAR to a minecraft 1.19 instance.
2. Make sure no `config/discordant/` folder exists yet.
3. Start the server (see first exception).
4. Type `/stop` to stop the server (see second exception).

### Actual Behaviour

On server start, this exception:
<details>
<pre>
[01:28:40] [main/INFO] (Minecraft) [STDERR]: javax.security.auth.login.LoginException: The provided token is invalid!
[01:28:40] [main/INFO] (Minecraft) [STDERR]: 	at net.dv8tion.jda.internal.JDAImpl.verifyToken(JDAImpl.java:389)
[01:28:40] [main/INFO] (Minecraft) [STDERR]: 	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:309)
[01:28:40] [main/INFO] (Minecraft) [STDERR]: 	at net.dv8tion.jda.internal.JDAImpl.login(JDAImpl.java:276)
[01:28:40] [main/INFO] (Minecraft) [STDERR]: 	at net.dv8tion.jda.api.JDABuilder.build(JDABuilder.java:1781)
[01:28:40] [main/INFO] (Minecraft) [STDERR]: 	at com.kwvanderlinde.discordant.discord.DiscordLink.initialize(DiscordLink.java:112)
[01:28:40] [main/INFO] (Minecraft) [STDERR]: 	at com.kwvanderlinde.discordant.discord.DiscordLink.onInitializeServer(DiscordLink.java:76)
[01:28:40] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
[01:28:40] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
[01:28:40] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63)
[01:28:40] [main/INFO] (Minecraft) [STDERR]: 	at net.minecraft.server.Main.main(Main.java:101)
[01:28:40] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
[01:28:40] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[01:28:40] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
[01:28:40] [main/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
</pre>
</details>

On server stop, this exception:
<details>
<pre>
[01:29:45] [Server thread/INFO] (Minecraft) Stopping the server
[01:29:46] [Server thread/ERROR] (Minecraft) Exception stopping the server
 java.lang.NullPointerException: Cannot invoke "net.dv8tion.jda.api.entities.TextChannel.getManager()" because "com.kwvanderlinde.discordant.discord.DiscordLink.chatChannel" is null
	at com.kwvanderlinde.discordant.discord.DiscordLink.setTopic(DiscordLink.java:265) ~[main/:?]
	at com.kwvanderlinde.discordant.discord.DiscordLink.shutdown(DiscordLink.java:269) ~[main/:?]
	at com.kwvanderlinde.discordant.discord.DiscordLink.lambda$onInitializeServer$4(DiscordLink.java:108) ~[main/:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:62) ~[fabric-lifecycle-events-v1-2.0.9+21a5acaaa9.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zdo000$beforeShutdownServer(MinecraftServer.java:2801) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.stopServer(MinecraftServer.java) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.dedicated.DedicatedServer.stopServer(DedicatedServer.java:547) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:697) ~[minecraft-project-@-merged-named.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:258) ~[minecraft-project-@-merged-named.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
</pre>
</details>

### Expected Behaviour

Instead of obscure exceptions, a server started without a valid configuration (especially for the default configuration or any other configuration that is just missing a token), a descriptive message should be printed to the console and no exception should escape. Also, the mod should either still be able to set itself up correctly, or it should get totally out of the way and not have operational issues later on.

### Discordant Version

develop

### Minecraft Version

1.19

### Fabric Loader Version

0.14.7

### Platform

Linux Mint 21

**Comment by kwvanderlinde** [comment]
Fixed by aa86ce5
